list: $/summer/kefu/models/kefusessionmodel/columns.yaml
modelClass: Summer\Kefu\Models\KefuSessionModel
title: KefuSession
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'summer/kefu/kefusession/update/:id'
