list: $/summer/kefu/models/kefukbsmodel/columns.yaml
modelClass: Summer\Kefu\Models\KefuKbsModel
title: KefuKbs
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'summer/kefu/kefukbs/update/:id'
