list: $/summer/kefu/models/kefuleavemessagemodel/columns.yaml
modelClass: Summer\Kefu\Models\KefuLeaveMessageModel
title: KefuLeaveMessage
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'summer/kefu/kefuleavemessage/update/:id'
