list: $/summer/kefu/models/kefucsrmodel/columns.yaml
modelClass: Summer\Kefu\Models\KefuCsrModel
title: KefuCsr
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'summer/kefu/kefucsr/update/:id'
